// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgQ2bKWSW7nRzbrIR9f8USKgELpRm_rdg',
    appId: '1:894438475281:web:d2396ad980b31312c513b0',
    messagingSenderId: '894438475281',
    projectId: 'keneni-91a60',
    authDomain: 'keneni-91a60.firebaseapp.com',
    storageBucket: 'keneni-91a60.firebasestorage.app',
    measurementId: 'G-PYQZ9DZ5BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASlSDBBmdDx7QOtf_Yg7Cyq8HzUXNLPH8',
    appId: '1:894438475281:android:25a68b9bf93d66fdc513b0',
    messagingSenderId: '894438475281',
    projectId: 'keneni-91a60',
    storageBucket: 'keneni-91a60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm_PUmjtfIKRio690iqC-nQorX1r_7g1g',
    appId: '1:894438475281:ios:216ddd65dee8026ac513b0',
    messagingSenderId: '894438475281',
    projectId: 'keneni-91a60',
    storageBucket: 'keneni-91a60.firebasestorage.app',
    iosBundleId: 'com.example.keneniapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm_PUmjtfIKRio690iqC-nQorX1r_7g1g',
    appId: '1:894438475281:ios:216ddd65dee8026ac513b0',
    messagingSenderId: '894438475281',
    projectId: 'keneni-91a60',
    storageBucket: 'keneni-91a60.firebasestorage.app',
    iosBundleId: 'com.example.keneniapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgQ2bKWSW7nRzbrIR9f8USKgELpRm_rdg',
    appId: '1:894438475281:web:153ab2261f8db642c513b0',
    messagingSenderId: '894438475281',
    projectId: 'keneni-91a60',
    authDomain: 'keneni-91a60.firebaseapp.com',
    storageBucket: 'keneni-91a60.firebasestorage.app',
    measurementId: 'G-02E3VFY81X',
  );
}
